[build]
  command = "npm run build:lambda"
  functions = "lambda"

service = "fileupload"
[provider]
    name = "aws"
    runtime = "nodejs4.3"
  [[provider.iamRoleStatements]]
    Effect = "Allow"
    Action = [ "s3:*" ]
    Resource = "arn:aws:s3:::slsupload/*"
[functions]
  [functions.test]
    handler = "handler.test"
  [functions.requestUploadURL]
    handler = "handler.requestUploadURL"
    [[functions.requestUploadURL.events]]
    [functions.requestUploadURL.events.http]
      path = "requestUploadURL"
      method = "post"
      cors = true
[resources]
  [resources.Resources]
    [resources.Resources.UploadBucket]
    Type = "AWS::S3::Bucket"
      [resources.Resources.UploadBucket.Properties]
      BucketName = "slsupload"
      AccessControl = "PublicRead"
        [resources.Resources.UploadBucket.Properties.CorsConfiguration]
          [[resources.Resources.UploadBucket.Properties.CorsConfiguration.CorsRules]]
          AllowedMethods = [ "GET", "PUT", "POST", "HEAD" ]
          AllowedOrigins = [ "*" ]
          AllowedHeaders = [ "*" ]
