-- psql.exe -U postgres -d userdb -f .\02_DBMigration.psql

CREATE TABLE IF NOT EXISTS session (
    id CHAR(36) NOT NULL,
    expiration BIGINT NOT NULL,
    user_id BIGINT NULL,
    deleted BOOLEAN NOT NULL DEFAULT false);

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(512) NOT NULL,
    password VARCHAR(64) NOT NULL,
    first_name VARCHAR(64) NULL,
    last_name VARCHAR(64) NULL);

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users (email);


